import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import "./shapes.css";
import "./layout.css";
import NavBar from "@/components/nav_bar";
import { AnimatePresence } from "motion/react";

const fnt = Poppins({
  subsets: ["latin"],
  weight: '400'
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${fnt.className}`}>
        <main id="main-container">
          <NavBar />
          <div className="child-container">
            <AnimatePresence >{children}</AnimatePresence>          
          </div>
          <footer id="footer" >Footer</footer>
        </main>
      </body>
    </html>
  );
}

