export const WORDS = [
    "Games",
    "Websites",
    "Social Media",
    "Utilities",
    "Scripts",
    "Mistakes",
    "Web Apps",
    "Maquettes",
    "Layouts",
    "Websites",
    "Bots",
    "Modals",
    "Trades",
    "Plugins",
    "Styles",
    "Soup",
    "Textures",
    "Models",
    "Paintings",
    "Drawings",
    "Applications",
    "Movies",
    "Motion Graphics",
    "Composites",
    "Coffee"
]